<?xml version="1.0" encoding="utf-8"?><Database Name="antran2598_test" Class="MydbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql.bsite.net\MSSQL2016;Initial Catalog=antran2598_test;Persist Security Info=True;User ID=antran2598_test" SettingsObjectName="NV_SHARED.Properties.Settings" SettingsPropertyName="antran2598_testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChitietNV" Member="ChitietNVs">
    <Type Name="ChitietNV">
      <Column Name="Manv" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chucvu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phongban" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chuthich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>